---
- name: Configure common hosts
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - common

- name: Configure Master nodes
  hosts: masters
  become: yes
  gather_facts: yes
  vars_prompt:
    - name: codebattle_db_password
      prompt: Enter postgres password
  roles:
    - master

- name: Configure Worker nodes
  hosts: workers
  become: yes
  gather_facts: yes
  roles:
    - worker
