---
- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted

- name: reload postgresql
  systemd:
    name: postgresql
    state: reloaded

- name: restart k3s
  systemd:
    name: k3s
    state: restarted