---
- name: restart sshd
  systemd:
    name: sshd
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded

- name: restart network
  systemd:
    name: NetworkManager
    state: restarted