---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Generate hosts entries for all inventory hosts
  set_fact:
    all_hosts_entries: |
      {% for host in groups['all'] %}
      {{ hostvars[host]['ansible_host'] }} {{ host }}
      {% endfor %}

- name: Update /etc/hosts with all inventory hosts
  blockinfile:
    path: /etc/hosts
    block: "{{ all_hosts_entries }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Inventory hosts"
    backup: yes

- name: Ensure localhost entries are present
  lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - {
        regexp: '^127\.0\.0\.1\s+localhost',
        line: "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4",
      }
    - {
        regexp: '^::1\s+localhost',
        line: "::1 localhost localhost.localdomain localhost6 localhost6.localdomain6",
      }
