---
- name: restart k3s-agent
  systemd:
    name: k3s-agent
    state: restarted

- name: stop k3s-agent
  systemd:
    name: k3s-agent
    state: stopped

- name: start k3s-agent
  systemd:
    name: k3s-agent
    state: started